- name: Disable swap temporarily
  command: swapoff -a
  register: swapoff_result
  when: ansible_facts["swaptotal_mb"] > 0
  changed_when: ansible_facts["swaptotal_mb"] > 0

- name: Comment out swap entries in /etc/fstab
  replace:
    path: /etc/fstab
    regexp: "^([^#].*swap.*)$"
    replace: '# \1'
    backup: yes

- name: hushlogin
  file:
    path: .hushlogin
    state: touch
    owner: "{{ k8s_admin_user }}"
    group: "{{ k8s_admin_user }}"
    mode: '0644'

- name: Add kubectl alias
  lineinfile:
    path: .bashrc
    line: "alias k='kubectl'"
    state: present
    create: yes
    owner: "{{ k8s_admin_user }}"
    group: "{{ k8s_admin_user }}"
    mode: '0644'
