- name: Disable swap temporarily
  ansible.builtin.command: swapoff -a
  register: common_swapoff_result
  when: ansible_facts["swaptotal_mb"] > 0
  changed_when: ansible_facts["swaptotal_mb"] > 0

- name: Comment out swap entries in /etc/fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: "^([^#].*swap.*)$"
    replace: '# \1'
    backup: true

- name: Create .hushlogin
  ansible.builtin.file:
    path: .hushlogin
    state: touch
    owner: "{{ k8s_admin_user }}"
    group: "{{ k8s_admin_user }}"
    mode: '0644'

- name: Add kubectl alias
  ansible.builtin.lineinfile:
    path: .bashrc
    line: "alias k='kubectl'"
    state: present
    create: true
    owner: "{{ k8s_admin_user }}"
    group: "{{ k8s_admin_user }}"
    mode: '0644'
