- name: Setup Kubernetes Nodes
  hosts: k8s_nodes
  become: true
  roles:
    - common
    - containerd
    - k8s_prereqs

- name: Configure Control Plane
  hosts: k8s_master
  become: true
  roles:
    - k8s_master

- name: Join Worker Nodes
  hosts: k8s_workers
  become: true
  roles:
    - k8s_worker
